### ISSUE TITLE
Nodejs device code disconnects for no reason

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks-preview#10] opened 2016-11-17 13:52 UTC
I am running the device using node v 7 to test and occasionally try to send msgs from cloud. I am running the sample as is from this repository.  Next day I try to send a message to the device and shows that it is disconnected in the DeviceExplorer. Once I restart the device it shows connected and message from cloud is received a expected. The issue is why would it disconnect without any reason? I listen on disconnect event and log the message. There are no messages about disconnect in the log as well. 

I have two instances of this running and both have the same issue. Please help.

```
"azure-iot-device": "^1.1.0-dtpreview.2",
"azure-iot-device-mqtt": "^1.1.0-dtpreview.2"
```

Thanks

**Comment by pierreca** [comment] 2016-12-14 19:34
Looks like the issue is opened there too: https://github.com/Azure/azure-iot-sdks/issues/980
Closing this one since this repo is currently defunct (The device management preview shipped into the production SDKs and is no more a preview)

**Closed** 2016-12-14 20:15 UTC
